apiVersion: apps/v1
kind: Deployment
metadata:
  name: rssvc-deployment
  labels:
    app: rssvc
    hail.is/sha: "{{ code.sha }}"
spec:
  selector:
    matchLabels:
      app: rssvc
  replicas: 1
  template:
    metadata:
      labels:
        app: rssvc
        hail.is/sha: "{{ code.sha }}"
    spec:
{% if deploy %}
      priorityClassName: production
{% endif %}
      nodeSelector:
        preemptible: "true"
      tolerations:
       - key: preemptible
         value: "true"
      containers:
      - name: rssvc
        image: "{{ rssvc_image.image }}"
        resources:
          requests:
            cpu: "20m"
            memory: "20M"
          limits:
            cpu: "1"
            memory: "1G"
        env:
          - name: RUST_LOG
            value: "info"
        ports:
        - containerPort: 5000
        readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
        livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rssvc
  labels:
    app: rssvc
spec:
  ports:
  - name: tcp
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: rssvc
